reworked console code

diff --git a/setsysfont b/setsysfont
--- a/setsysfont
+++ b/setsysfont
@@ -49,7 +49,7 @@ elif [ -n "$SETFONT" ]; then
 		"$SETFONT" "$SYSFONT"
 	fi
 else
-	echo "cannot set font" >&2
+	echo "${0##*/}: cannot set font" >&2
 	exit 1
 fi
 :
