rewritten BOOTUP-related code; updated daemon function

diff --git a/rc.d/init.d/functions b/rc.d/init.d/functions
--- a/rc.d/init.d/functions
+++ b/rc.d/init.d/functions
@@ -39,28 +39,30 @@ ExecIfExecutable()
 
 # Read in our configuration
 if [ -z "$BOOTUP" ]; then
-  if ! SourceIfNotEmpty /etc/sysconfig/init; then
-    # This all seem confusing? Look in /etc/sysconfig/init,
-    # or in /usr/doc/initscripts-*/sysconfig.txt
-    BOOTUP=color
-    RES_COL=60
-    MOVE_TO_COL="echo -en \\033[${RES_COL}G"
-    SETCOLOR_SUCCESS="echo -en \\033[1;32m"
-    SETCOLOR_FAILURE="echo -en \\033[1;31m"
-    SETCOLOR_WARNING="echo -en \\033[1;33m"
-    SETCOLOR_NORMAL="echo -en \\033[0;39m"
-    LOGLEVEL=1
-  fi
-  if [ -x /sbin/consoletype ]; then
-    if [ "`consoletype`" = "serial" ]; then
-      BOOTUP=serial
-      MOVE_TO_COL=
-      SETCOLOR_SUCCESS=
-      SETCOLOR_FAILURE=
-      SETCOLOR_WARNING=
-      SETCOLOR_NORMAL=
-    fi
-  fi
+	if ! SourceIfNotEmpty /etc/sysconfig/init; then
+		# This all seem confusing? Look in /etc/sysconfig/init,
+		# or in /usr/share/doc/initscripts-*/sysconfig.txt
+		BOOTUP=color
+		RES_COL=60
+		MOVE_TO_COL="echo -en \\033[${RES_COL}G"
+		SETCOLOR_SUCCESS="echo -en \\033[1;32m"
+		SETCOLOR_FAILURE="echo -en \\033[1;31m"
+		SETCOLOR_WARNING="echo -en \\033[1;33m"
+		SETCOLOR_NORMAL="echo -en \\033[0;39m"
+		LOGLEVEL=1
+	fi
+fi
+
+if [ -x /sbin/consoletype ] && [ "`consoletype`" = "serial" ]; then
+	BOOTUP=serial
+fi
+
+if [ "$BOOTUP" != "color" ]; then
+	MOVE_TO_COL=:
+	SETCOLOR_SUCCESS=:
+	SETCOLOR_FAILURE=:
+	SETCOLOR_WARNING=:
+	SETCOLOR_NORMAL=:
 fi
 
 if [ "$BOOTUP" != "verbose" ]; then
@@ -72,12 +74,11 @@ fi
 # Check if $pid (could be plural) are running
 checkpid() {
 	while [ "$1" ]; do
-	   [ -d /proc/$1 ] && return 0
+	   [ -d "/proc/$1" ] && return 0
 	   shift
 	done
 	return 1
 }
-	
 
 # A function to start a program.
 daemon() {
@@ -108,11 +109,11 @@ daemon() {
 	  esac
 	done
 
-        # Save basename.
-        [ -z $gotbase ] && base="${1##*/}"
+	# Save basename.
+	[ -z $gotbase ] && base="${1##*/}"
 
-        # See if it's already running.
-        pidlist=`pidofproc $1`
+	# See if it's already running.
+	pidlist=`pidofproc $1`
 	
 	pid=
 	for apid in $pidlist ; do
@@ -121,9 +122,9 @@ daemon() {
 
 	
 	# Echo daemon
-	[ "$BOOTUP" = "verbose" ] && echo -n " $base"
+	if [ "$BOOTUP" = "verbose" ]; then echo -n "$base "; fi
 
-	[ -n "$pid" ] && { echo_passed ; return ; }
+	[ -n "$pid" ] && { echo_passed; return; }
 
 	# make sure it doesn't core dump anywhere; while this could mask
 	# problems with the daemon, it also closes some security problems
@@ -131,10 +132,29 @@ daemon() {
 	
 	# And start it up.
 	if [ -z "$daemon_user" ]; then 
-	   nice -n $nicelevel initlog $INITLOG_ARGS -c "$*" && success "$base startup" || failure "$base startup"
+		nice -n $nicelevel initlog $INITLOG_ARGS -c "$*" && success "$base startup" || failure "$base startup"
 	else
-	   nice -n $nicelevel initlog $INITLOG_ARGS -c "su - $daemon_user -c \"$*\" -s /bin/sh" && success "$base startup" || failure "$base startup"
+		nice -n $nicelevel initlog $INITLOG_ARGS -c "su - $daemon_user -c \"$*\" -s /bin/sh" && success "$base startup" || failure "$base startup"
 	fi
+}
+
+# usage: wait_pid <w_pid> <w_times> <w_delay>
+wait_pid()
+{
+	local w_pid="$1"
+	shift
+	local w_times="$1"
+	shift
+	local w_delay="$1"
+	shift
+
+	local i=0
+	while [ $i -lt "$w_times" ]; do
+		checkpid "$w_pid" &>/dev/null || return 0
+		usleep "$w_delay"
+		i=$[1+i]
+	done
+	! checkpid "$w_pid"
 }
 
 # A function to stop a program.
@@ -155,44 +175,37 @@ killproc() {
 		killlevel="-9"
 	fi
 
-        # Save basename.
-        base="${1##*/}"
+	# Save basename.
+	base="${1##*/}"
 
-        # Find pid.
-        pidlist=`pidofproc $1`
+	# Find pid.
+	pidlist=`pidofproc $1`
 	
 	pid=
 	for apid in $pidlist ; do
 	   [ -d /proc/$apid ] && pid="$pid $apid"
 	done
 
-        # Kill it.
-        if [ "$pid" != "" ] ; then
-                [ $BOOTUP = "verbose" ] && echo -n "$base "
+	# Kill it.
+	if [ -n "$pid" ]; then
+		if [ "$BOOTUP" = "verbose" ]; then echo -n "$base "; fi
 		if [ "$notset" = "1" ] ; then
-		       if checkpid $pid 2>&1; then
-			   # TERM first, then KILL if not dead
-			   kill -TERM $pid
-			   usleep 100000
-			   if checkpid $pid >/dev/null 2>&1 ; then
-				sleep 1
-				if checkpid $pid >/dev/null 2>&1 ; then
-				        sleep 3
-					if checkpid $pid >/dev/null 2>&1 ; then
-					   kill -KILL $pid
-					   usleep 100000
-					fi
+			if checkpid "$pid" 2>&1; then
+				# TERM first, then KILL if not dead
+				kill -TERM "$pid"
+				if ! wait_pid "$pid" 30 100000; then
+					kill -KILL "$pid"
+					usleep 100000
 				fi
-			   fi
-		        fi
-			checkpid $pid >/dev/null 2>&1
+			fi
+			checkpid "$pid" &>/dev/null
 			RC=$?
 			[ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
 			RC=$((! $RC))
 		# use specified level only
 		else
-		        if checkpid $pid >/dev/null 2>&1; then
-	                	kill $killlevel $pid
+			if checkpid "$pid" &>/dev/null; then
+				kill "$killlevel" "$pid"
 				RC=$?
 				[ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
 			fi
@@ -201,9 +214,9 @@ killproc() {
 	    failure "$base shutdown"
 	fi
 
-        # Remove pid file if any.
+	# Remove pid file if any.
 	if [ "$notset" = "1" ]; then
-            rm -f /var/run/$base.pid
+		rm -f "/var/run/$base.pid"
 	fi
 	return $RC
 }
@@ -269,36 +282,33 @@ status() {
 }
 
 echo_success() {
-  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
-  echo -n "[  "
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
-  echo -n "OK"
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  echo -n "  ]"
-  echo -ne "\r"
-  return 0
+	$MOVE_TO_COL
+	echo -n "[  "
+	$SETCOLOR_SUCCESS
+	echo -n "OK"
+	$SETCOLOR_NORMAL
+	echo -n "  ]"
+	return 0
 }
 
 echo_failure() {
-  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
-  echo -n "["
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-  echo -n "FAILED"
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  echo -n "]"
-  echo -ne "\r"
-  return 1
+	$MOVE_TO_COL
+	echo -n "["
+	$SETCOLOR_FAILURE
+	echo -n "FAILED"
+	$SETCOLOR_NORMAL
+	echo -n "]"
+	return 1
 }
 
 echo_passed() {
-  [ "$BOOTUP" = "color" ] && $MOVE_TO_COL
-  echo -n "["
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-  echo -n "PASSED"
-  [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  echo -n "]"
-  echo -ne "\r"
-  return 1
+	$MOVE_TO_COL
+	echo -n "["
+	$SETCOLOR_WARNING
+	echo -n "PASSED"
+	$SETCOLOR_NORMAL
+	echo -n "]"
+	return 1
 }
 
 # Log that something succeeded
@@ -311,7 +321,7 @@ success() {
      echo "$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
      trap - SIGPIPE
   fi
-  [ "$BOOTUP" != "verbose" ] && echo_success
+  echo_success
   return 0
 }
 
@@ -325,7 +335,7 @@ failure() {
      echo "$INITLOG_ARGS -n $0 -s \"$1\" -e 2" >&21
      trap - SIGPIPE
   fi
-  [ "$BOOTUP" != "verbose" ] && echo_failure
+  echo_failure
   return $rc
 }
 
@@ -339,7 +349,7 @@ passed() {
      echo "$INITLOG_ARGS -n $0 -s \"$1\" -e 1" >&21
      trap - SIGPIPE
   fi
-  [ "$BOOTUP" != "verbose" ] && echo_passed
+  echo_passed
   return $rc
 }  
 
